### ISSUE TITLE
Missing election data for US Senate HI

### ISSUE THREAD

**Issue by spencer-rdh** [MEDSL/2022-elections-official#2]
Hello! I noticed that you are missing the results for US Senate candidates Dan Decker and Feena M. Bonoan for  Precinct 01-01 in Hawai'i County, Hawai'i. 

The results should be as follows: Bonoan 35 mail and 4 in person , Decker 19 mail and 0 in person. 

You can confirm these numbers [here](https://elections.hawaii.gov/wp-content/results/precinct.pdf) on pages 1 and 2.

The party_detailed field appears incorrect for the majority of candidates as well as most are listed as Aloha Aina Party.

**Comment by sbaltzmit** [comment]
Thanks very much for pointing out the problem and sorry I forgot to actually respond and close this Issue. There was a typo in the cleaning script that skipped the first two rows of the raw data. I've updated it and re-uploaded the cleaned data. Hopefully the issue is solved. Thanks again

**Comment by sbaltzmit** [comment]
Hmm, are you seeing the most recent version now? In the Aloha Aina Party I see `DAN DECKER` and `LEONARD K NAKOA`

**Comment by spencer-rdh** [comment]
Ah okay yeah I see it does look better now. I had downloaded a version at 4:01pm that had the corrected two candidates for US Senate but the parties were still incorrect. I see that in a latest version, the parties are also corrected. Thank you!
